version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  Socket_Service:
    image: socket_service
    build:
      context: ./Socket_Service
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3005:3005"
    env_file:
      - ./Socket_Service/.env
    depends_on:
      - redis

  Submission_Service:
    image: submission_service
    build:
      context: ./Submission_Service
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "7000:7000"
    env_file:
      - ./Submission_Service/.env
    depends_on:
      - redis
      - Socket_Service

  Evaluator_Service:
    image: evaluator_service
    build:
      context: ./Evaluator_Service
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./Evaluator_Service/.env
    depends_on:
      - redis
      - Submission_Service
      - Socket_Service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/oj-submissions:/tmp/oj-submissions

volumes:
  redis_data: